### PR TITLE
fixed translation command

### PR DESCRIPTION
**Pull request by emilycxliu**

### CODE REVIEW

**Comment by emilycxliu** [comment]
i changed the file names but they aren't shown in the pull request

**Review by weizhang-2706 — APPROVED** [review]

**Comment by ErikCald** [comment]
The file name is very important for Java, it won't compile if the filename doesn't match the class name.

Your branch on GitHub doesn't have the filename change. What we should see on GitHub is a commit that "deletes" translationCommand and "creates" TranslationCommand, but in VSCode that's just renaming the file.

**Review by ErikCald — CHANGES_REQUESTED** [review]
The filename also needs to be correct.

I'm pretty sure if you change the name to TranslationComman.java, commit it, then change the name to TranslationCommand.java, commit it, it should work.

**Comment by weizhang-2706** [comment]
In her VScode, file names are already changed. Just pull request still has the old file names.
Will figure it out tonight.

**Comment by emilycxliu** [comment]
i was finally able to change the file name. it should work now

**Review by ErikCald — APPROVED** [review]

**Pull request merged**
